In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ctl-exp.tsv", sep="\t")
df.columns = ["id", "baseMean", "log2FoldChange", "lfcSE", "stat", "pvalue", "padj"]
df

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSSSCG00000000002,63.002392,-0.308150,0.328892,-0.936935,3.487923e-01,5.135374e-01
1,ENSSSCG00000000003,38.995692,-0.235587,0.422692,-0.557350,5.772881e-01,7.157913e-01
2,ENSSSCG00000000005,23.174388,0.632312,0.489968,1.290517,1.968712e-01,3.438576e-01
3,ENSSSCG00000000006,29.874874,-0.010760,0.444249,-0.024221,9.806760e-01,9.894972e-01
4,ENSSSCG00000000007,76.945128,0.339734,0.277949,1.222287,2.215992e-01,3.741391e-01
...,...,...,...,...,...,...,...
19826,ENSSSCG00000051791,2.054076,0.703144,1.645976,0.427190,6.692409e-01,NaN
19827,ENSSSCG00000051793,0.789232,-2.834013,2.738001,-1.035066,3.006380e-01,NaN
19828,ENSSSCG00000051794,276.605891,0.509923,0.166904,3.055181,2.249244e-03,9.123363e-03
19829,ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07
19830,ENSSSCG00000051797,0.258776,-1.229996,4.043081,-0.304222,7.609585e-01,NaN

In [7]:
df_allVar = df[(df["log2FoldChange"].abs()>1)&(df["pvalue"]<0.05)]
df_allVar.set_index("id", inplace=True)
df_allVar

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
id,,,,,,
ENSSSCG00000000014,102.696631,1.064760,0.284981,3.736245,1.867889e-04,1.034237e-03
ENSSSCG00000000063,184.452051,1.236392,0.187329,6.600106,4.108626e-11,7.354960e-10
ENSSSCG00000000084,1236.775757,1.785623,0.135140,13.213123,7.370218e-40,9.821918e-38
ENSSSCG00000000092,32.015411,-1.254268,0.442818,-2.832469,4.619007e-03,1.691791e-02
ENSSSCG00000000142,77.643948,1.653824,0.290603,5.691000,1.262975e-08,1.560405e-07
...,...,...,...,...,...,...
ENSSSCG00000051721,15.490371,-1.855634,0.691739,-2.682564,7.306008e-03,2.486690e-02
ENSSSCG00000051750,30.137922,-1.309836,0.471116,-2.780286,5.431107e-03,1.932493e-02
ENSSSCG00000051773,2.408691,-4.433786,2.050997,-2.161771,3.063580e-02,NaN
ENSSSCG00000051776,8.199226,-2.130959,1.019445,-2.090313,3.658969e-02,9.372539e-02
ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07

In [17]:
df_tpm = pd.read_csv("../star_rsem/rsem.merged.gene_tpm.tsv", sep="\t")
df_tpm.set_index("gene_id", inplace = True)
df_tpm.drop(columns=["transcript_id(s)"]).loc[df_allVar.index].to_csv("allDiff_tpm.txt", sep="\t")

In [18]:
!python id2name1.py gene.bed allDiff_tpm.txt allDiff_tpm.csv

In [19]:
!head allDiff_tpm.txt

id	TGEV_REP1	TGEV_REP2	TGEV_REP3	WT_REP1	WT_REP2	WT_REP3
ENSSSCG00000000014	7.67	11.56	11.64	5.36	3.5	3.8
ENSSSCG00000000063	17.23	14.82	15.49	6.47	6.14	5.53
ENSSSCG00000000084	54.4	63.77	60.11	13.73	17.36	13.54
ENSSSCG00000000092	0.71	0.41	0.58	1.36	0.99	1.11
ENSSSCG00000000142	3.61	3.65	4.86	0.93	1.06	1.22
ENSSSCG00000000197	0.25	0.0	0.58	1.02	1.23	0.7
ENSSSCG00000000232	0.0	0.08	0.0	0.21	0.09	0.18
ENSSSCG00000000258	0.89	0.84	0.27	1.41	1.51	1.23
ENSSSCG00000000368	7.69	4.15	3.11	8.97	8.39	8.8

In [20]:
!head allDiff_tpm.csv

gene_id	TGEV_REP1	TGEV_REP2	TGEV_REP3	WT_REP1	WT_REP2	WT_REP3
FAM118A	7.67	11.56	11.64	5.36	3.5	3.8
POLR3H	17.23	14.82	15.49	6.47	6.14	5.53
ATF4	54.4	63.77	60.11	13.73	17.36	13.54
NPTXR	0.71	0.41	0.58	1.36	0.99	1.11
FOXRED2	3.61	3.65	4.86	0.93	1.06	1.22
C1QL4	0.25	0.0	0.58	1.02	1.23	0.7
ACVRL1	0.0	0.08	0.0	0.21	0.09	0.18
RARG	0.89	0.84	0.27	1.41	1.51	1.23
MMP19	7.69	4.15	3.11	8.97	8.39	8.8

In [24]:
!python id2name.py gene.bed ctl-exp.tsv ctl-exp_name.csv

In [25]:
!head ctl-exp_name.csv

	baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
GTSE1	63.0023921933113	-0.308150265899188	0.328892004189366	-0.936934501216285	0.348792250794352	0.513537419538704
TTC38	38.9956919299181	-0.235587314100923	0.422691617127798	-0.557350334273828	0.577288091777072	0.715791326201838
CDPF1	23.174387650231	0.632311628801645	0.489967722110628	1.29051690604811	0.196871245828082	0.343857563005651
PPARA	29.8748740390392	-0.0107603352430285	0.444249470554258	-0.0242213800043557	0.980676024354696	0.989497222011158
TRMU	76.9451278055653	0.339733631506374	0.277949184885168	1.22228684227562	0.221599173229462	0.37413906973403
FBLN1	14.4059280881763	-0.290013422622822	0.728028420776186	-0.398354534447466	0.69036886682443	0.803900774572555
FAM118A	102.696631460318	1.06476040454636	0.284981440060991	3.7362447334061	0.000186788881631075	0.0010342373019857
KIAA0930	291.704600484436	-0.238416869650059	0.1576054550653	-1.5127450350705	0.130344435365273	0.251805000507794
NUP50	568.126536390054	0.382665245449053	0.139972243480744	2.73386520022234	0.00625956648618504	0.0218440377467764

In [26]:
!head ctl-exp.tsv

	baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
ENSSSCG00000000002	63.0023921933113	-0.308150265899188	0.328892004189366	-0.936934501216285	0.348792250794352	0.513537419538704
ENSSSCG00000000003	38.9956919299181	-0.235587314100923	0.422691617127798	-0.557350334273828	0.577288091777072	0.715791326201838
ENSSSCG00000000005	23.174387650231	0.632311628801645	0.489967722110628	1.29051690604811	0.196871245828082	0.343857563005651
ENSSSCG00000000006	29.8748740390392	-0.0107603352430285	0.444249470554258	-0.0242213800043557	0.980676024354696	0.989497222011158
ENSSSCG00000000007	76.9451278055653	0.339733631506374	0.277949184885168	1.22228684227562	0.221599173229462	0.37413906973403
ENSSSCG00000000010	14.4059280881763	-0.290013422622822	0.728028420776186	-0.398354534447466	0.69036886682443	0.803900774572555
ENSSSCG00000000014	102.696631460318	1.06476040454636	0.284981440060991	3.7362447334061	0.000186788881631075	0.0010342373019857
ENSSSCG00000000018	291.704600484436	-0.238416869650059	0.1576054550653	-1.5127450350705	0.130344435365273	0.251805000507794
ENSSSCG00000000019	568.126536390054	0.382665245449053	0.139972243480744	2.73386520022234	0.00625956648618504	0.0218440377467764