In [70]:
import pandas as pd
from tqdm.notebook import tqdm

In [71]:
df = pd.read_csv("ctl-exp.tsv", sep="\t")
df.columns = ["id", "baseMean", "log2FoldChange", "lfcSE", "stat", "pvalue", "padj"]
df

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSSSCG00000000002,63.002392,-0.308150,0.328892,-0.936935,3.487923e-01,5.135374e-01
1,ENSSSCG00000000003,38.995692,-0.235587,0.422692,-0.557350,5.772881e-01,7.157913e-01
2,ENSSSCG00000000005,23.174388,0.632312,0.489968,1.290517,1.968712e-01,3.438576e-01
3,ENSSSCG00000000006,29.874874,-0.010760,0.444249,-0.024221,9.806760e-01,9.894972e-01
4,ENSSSCG00000000007,76.945128,0.339734,0.277949,1.222287,2.215992e-01,3.741391e-01
...,...,...,...,...,...,...,...
19826,ENSSSCG00000051791,2.054076,0.703144,1.645976,0.427190,6.692409e-01,NaN
19827,ENSSSCG00000051793,0.789232,-2.834013,2.738001,-1.035066,3.006380e-01,NaN
19828,ENSSSCG00000051794,276.605891,0.509923,0.166904,3.055181,2.249244e-03,9.123363e-03
19829,ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07
19830,ENSSSCG00000051797,0.258776,-1.229996,4.043081,-0.304222,7.609585e-01,NaN

In [72]:
df_allVar = df[(df["log2FoldChange"].abs()>1)&(df["pvalue"]<0.05)]
df_allVar

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
6,ENSSSCG00000000014,102.696631,1.064760,0.284981,3.736245,1.867889e-04,1.034237e-03
33,ENSSSCG00000000063,184.452051,1.236392,0.187329,6.600106,4.108626e-11,7.354960e-10
48,ENSSSCG00000000084,1236.775757,1.785623,0.135140,13.213123,7.370218e-40,9.821918e-38
51,ENSSSCG00000000092,32.015411,-1.254268,0.442818,-2.832469,4.619007e-03,1.691791e-02
78,ENSSSCG00000000142,77.643948,1.653824,0.290603,5.691000,1.262975e-08,1.560405e-07
...,...,...,...,...,...,...,...
19789,ENSSSCG00000051721,15.490371,-1.855634,0.691739,-2.682564,7.306008e-03,2.486690e-02
19802,ENSSSCG00000051750,30.137922,-1.309836,0.471116,-2.780286,5.431107e-03,1.932493e-02
19815,ENSSSCG00000051773,2.408691,-4.433786,2.050997,-2.161771,3.063580e-02,NaN
19817,ENSSSCG00000051776,8.199226,-2.130959,1.019445,-2.090313,3.658969e-02,9.372539e-02
19829,ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07

In [73]:
df_up = df[(df["log2FoldChange"]>1)&(df["pvalue"]<0.05)]
df_top50Up = df_up.sort_values(["log2FoldChange"],ascending = [False]).head(50)
df_top50Up.head()

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
10754,ENSSSCG00000029403,36.989598,8.952531,3.908221,2.290692,2.198122e-02,6.205526e-02
4806,ENSSSCG00000010376,34.333064,6.967537,1.089300,6.396346,1.591391e-10,2.606404e-09
8581,ENSSSCG00000020970,116.416052,6.743786,0.559326,12.056981,1.781965e-33,1.804182e-31
8720,ENSSSCG00000021569,88.144300,6.341461,0.582559,10.885533,1.351054e-27,1.032629e-25
279,ENSSSCG00000000668,132.768619,6.117736,0.441050,13.870841,9.515431e-44,1.454555e-41

In [74]:
df_down = df[(df["log2FoldChange"]<-1)&(df["pvalue"]<0.05)]
df_top50Down = df_down.sort_values(["log2FoldChange"],ascending = [True]).head(50)
df_top50Down.head()

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
5299,ENSSSCG00000011369,136.686923,-10.266445,1.195436,-8.588037,8.846761e-18,3.276453e-16
4191,ENSSSCG00000009221,16.032115,-7.173050,1.299970,-5.517856,3.431604e-08,3.957512e-07
19411,ENSSSCG00000051006,6.773860,-5.933852,1.458195,-4.069312,4.715213e-05,3.002026e-04
16843,ENSSSCG00000045881,6.300272,-5.821209,1.497726,-3.886698,1.016169e-04,6.003827e-04
15425,ENSSSCG00000043021,5.573482,-5.655179,1.587718,-3.561829,3.682799e-04,1.892000e-03

In [75]:
df_top100 = pd.concat([df_top50Up, df_top50Down], axis=0)

In [76]:
df_top100.set_index("id", inplace = True)
df_top100

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
id,,,,,,
ENSSSCG00000029403,36.989598,8.952531,3.908221,2.290692,2.198122e-02,6.205526e-02
ENSSSCG00000010376,34.333064,6.967537,1.089300,6.396346,1.591391e-10,2.606404e-09
ENSSSCG00000020970,116.416052,6.743786,0.559326,12.056981,1.781965e-33,1.804182e-31
ENSSSCG00000021569,88.144300,6.341461,0.582559,10.885533,1.351054e-27,1.032629e-25
ENSSSCG00000000668,132.768619,6.117736,0.441050,13.870841,9.515431e-44,1.454555e-41
...,...,...,...,...,...,...
ENSSSCG00000003227,2.066277,-4.215830,2.136472,-1.973267,4.846515e-02,NaN
ENSSSCG00000043903,2.060273,-4.211239,1.938933,-2.171936,2.986046e-02,NaN
ENSSSCG00000007674,2.056270,-4.208671,1.931247,-2.179250,2.931307e-02,NaN
ENSSSCG00000044189,2.037362,-4.196908,1.934644,-2.169344,3.005658e-02,NaN
ENSSSCG00000042848,2.033359,-4.194354,1.935365,-2.167216,3.021836e-02,NaN

In [77]:
df_tpm = pd.read_csv("../star_rsem/rsem.merged.gene_tpm.tsv", sep="\t")
df_tpm.set_index("gene_id", inplace = True)
df_tpm

,transcript_id(s),TGEV_REP1,TGEV_REP2,TGEV_REP3,WT_REP1,WT_REP2,WT_REP3
gene_id,,,,,,,
ENSSSCG00000000002,ENSSSCT00000000003,4.81,3.13,4.73,3.79,5.62,4.07
ENSSSCG00000000003,"ENSSSCT00000000004,ENSSSCT00000052628,ENSSSCT0...",2.19,2.65,3.76,1.81,2.85,4.39
ENSSSCG00000000005,ENSSSCT00000000006,1.60,2.28,1.48,1.03,1.08,0.86
ENSSSCG00000000006,ENSSSCT00000000007,0.91,1.72,1.25,0.88,1.23,1.33
ENSSSCG00000000007,"ENSSSCT00000000008,ENSSSCT00000057594,ENSSSCT0...",8.18,9.08,8.88,5.73,7.24,6.23
...,...,...,...,...,...,...,...
ENSSSCG00000051794,"ENSSSCT00000029953,ENSSSCT00000037685,ENSSSCT0...",15.97,14.91,13.70,9.19,7.75,10.58
ENSSSCG00000051795,ENSSSCT00000075332,0.04,0.03,0.06,1.03,0.88,1.46
ENSSSCG00000051796,ENSSSCT00000083535,0.00,0.00,0.13,0.00,0.00,0.00
ENSSSCG00000051797,ENSSSCT00000088271,0.00,0.00,0.00,0.00,0.04,0.00
ENSSSCG00000051798,ENSSSCT00000091644,0.00,0.00,0.00,0.00,0.00,0.00

In [78]:
df_tpm.drop(columns=["transcript_id(s)"]).loc[df_top100.index].to_csv("TOP100_variable_tpm.txt", sep='\t', index=True)

In [79]:
!head tmp.txt

id	TGEV_REP1	TGEV_REP2	TGEV_REP3	WT_REP1	WT_REP2	WT_REP3
ENSSSCG00000011369	0.0	0.0	0.0	6.22	6.49	6.53
ENSSSCG00000009221	0.0	0.0	0.0	0.84	1.03	1.27
ENSSSCG00000051006	0.0	0.0	0.0	0.3	0.42	0.24
ENSSSCG00000045881	0.0	0.0	0.0	0.24	0.19	0.65
ENSSSCG00000043021	0.03	0.0	0.0	0.27	0.44	0.05
ENSSSCG00000004676	0.0	0.0	0.0	0.15	0.73	0.04
ENSSSCG00000038839	0.0	0.0	0.0	0.39	0.4	0.28
ENSSSCG00000035052	0.0	0.0	0.0	0.37	0.51	1.04
ENSSSCG00000002512	0.2	0.0	0.0	0.83	2.95	2.04

In [80]:
!python id2name1.py gene.bed TOP100_variable_tpm.txt TOP100_variable_tpm.csv

In [81]:
!head TOP100_variable_tpm.txt

id	TGEV_REP1	TGEV_REP2	TGEV_REP3	WT_REP1	WT_REP2	WT_REP3
ENSSSCG00000029403	0.0	4.06	4.3	0.0	0.0	0.0
ENSSSCG00000010376	1.95	1.49	1.82	0.0	0.0	0.04
ENSSSCG00000020970	69.98	67.53	59.43	0.86	0.0	0.32
ENSSSCG00000021569	7.71	7.05	10.93	0.06	0.16	0.04
ENSSSCG00000000668	23.66	23.67	19.38	0.21	0.44	0.14
ENSSSCG00000047565	0.55	0.74	0.61	0.0	0.0	0.03
ENSSSCG00000010224	2.77	2.72	2.26	0.08	0.04	0.0
ENSSSCG00000016900	1.53	0.39	1.73	0.0	0.07	0.0
ENSSSCG00000050554	0.0	1.92	2.6	0.0	0.0	0.13

In [82]:
!tail TOP100_variable_tpm.txt

ENSSSCG00000033997	0.0	0.0	0.0	0.27	0.42	0.55
ENSSSCG00000045016	0.0	0.0	0.0	0.0	0.8	0.5
ENSSSCG00000042461	0.0	0.0	0.0	0.17	0.1	0.16
ENSSSCG00000042558	0.0	0.0	0.08	0.2	0.88	0.61
ENSSSCG00000037437	0.0	0.0	0.06	0.46	0.18	0.32
ENSSSCG00000003227	0.0	0.05	0.0	0.0	0.38	0.34
ENSSSCG00000043903	0.0	0.0	0.0	0.31	0.64	0.84
ENSSSCG00000007674	0.0	0.0	0.0	0.07	0.06	0.11
ENSSSCG00000044189	0.0	0.0	0.0	0.08	0.12	0.13
ENSSSCG00000042848	0.0	0.0	0.0	0.21	0.15	0.24