In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ctl-exp.tsv", sep="\t")
df.columns = ["id", "baseMean", "log2FoldChange", "lfcSE", "stat", "pvalue", "padj"]
df

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSSSCG00000000002,63.002392,-0.308150,0.328892,-0.936935,3.487923e-01,5.135374e-01
1,ENSSSCG00000000003,38.995692,-0.235587,0.422692,-0.557350,5.772881e-01,7.157913e-01
2,ENSSSCG00000000005,23.174388,0.632312,0.489968,1.290517,1.968712e-01,3.438576e-01
3,ENSSSCG00000000006,29.874874,-0.010760,0.444249,-0.024221,9.806760e-01,9.894972e-01
4,ENSSSCG00000000007,76.945128,0.339734,0.277949,1.222287,2.215992e-01,3.741391e-01
...,...,...,...,...,...,...,...
19826,ENSSSCG00000051791,2.054076,0.703144,1.645976,0.427190,6.692409e-01,NaN
19827,ENSSSCG00000051793,0.789232,-2.834013,2.738001,-1.035066,3.006380e-01,NaN
19828,ENSSSCG00000051794,276.605891,0.509923,0.166904,3.055181,2.249244e-03,9.123363e-03
19829,ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07
19830,ENSSSCG00000051797,0.258776,-1.229996,4.043081,-0.304222,7.609585e-01,NaN

In [8]:
df_up = df[(df["log2FoldChange"]>1)&(df["pvalue"]<0.05)]
df_up

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
6,ENSSSCG00000000014,102.696631,1.064760,0.284981,3.736245,1.867889e-04,1.034237e-03
33,ENSSSCG00000000063,184.452051,1.236392,0.187329,6.600106,4.108626e-11,7.354960e-10
48,ENSSSCG00000000084,1236.775757,1.785623,0.135140,13.213123,7.370218e-40,9.821918e-38
78,ENSSSCG00000000142,77.643948,1.653824,0.290603,5.691000,1.262975e-08,1.560405e-07
207,ENSSSCG00000000477,356.401060,1.121920,0.154973,7.239449,4.505107e-13,1.037572e-11
...,...,...,...,...,...,...,...
19710,ENSSSCG00000051577,2.635838,4.084968,1.782920,2.291167,2.195374e-02,NaN
19711,ENSSSCG00000051578,12.572240,2.094332,0.743188,2.818038,4.831807e-03,1.753259e-02
19730,ENSSSCG00000051612,72.432190,2.042324,0.293728,6.953103,3.573372e-12,7.264148e-11
19744,ENSSSCG00000051635,16.351380,1.868333,0.652173,2.864781,4.172982e-03,1.554351e-02
19759,ENSSSCG00000051661,305.648369,1.816064,0.195456,9.291420,1.522430e-20,7.349143e-19

In [24]:
df_up.set_index("id", inplace = True)
df_up

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
id,,,,,,
ENSSSCG00000000014,102.696631,1.064760,0.284981,3.736245,1.867889e-04,1.034237e-03
ENSSSCG00000000063,184.452051,1.236392,0.187329,6.600106,4.108626e-11,7.354960e-10
ENSSSCG00000000084,1236.775757,1.785623,0.135140,13.213123,7.370218e-40,9.821918e-38
ENSSSCG00000000142,77.643948,1.653824,0.290603,5.691000,1.262975e-08,1.560405e-07
ENSSSCG00000000477,356.401060,1.121920,0.154973,7.239449,4.505107e-13,1.037572e-11
...,...,...,...,...,...,...
ENSSSCG00000051577,2.635838,4.084968,1.782920,2.291167,2.195374e-02,NaN
ENSSSCG00000051578,12.572240,2.094332,0.743188,2.818038,4.831807e-03,1.753259e-02
ENSSSCG00000051612,72.432190,2.042324,0.293728,6.953103,3.573372e-12,7.264148e-11
ENSSSCG00000051635,16.351380,1.868333,0.652173,2.864781,4.172982e-03,1.554351e-02
ENSSSCG00000051661,305.648369,1.816064,0.195456,9.291420,1.522430e-20,7.349143e-19

In [6]:
df_down = df[(df["log2FoldChange"]<-1)&(df["pvalue"]<0.05)]
df_down

,id,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
51,ENSSSCG00000000092,32.015411,-1.254268,0.442818,-2.832469,4.619007e-03,1.691791e-02
105,ENSSSCG00000000197,8.740224,-2.010402,0.936963,-2.145657,3.190034e-02,8.376230e-02
118,ENSSSCG00000000232,3.315000,-3.851302,1.664316,-2.314045,2.066525e-02,5.894852e-02
126,ENSSSCG00000000258,17.796641,-1.387154,0.607078,-2.284968,2.231473e-02,6.281356e-02
161,ENSSSCG00000000368,58.881808,-1.065940,0.352353,-3.025204,2.484653e-03,9.961614e-03
...,...,...,...,...,...,...,...
19789,ENSSSCG00000051721,15.490371,-1.855634,0.691739,-2.682564,7.306008e-03,2.486690e-02
19802,ENSSSCG00000051750,30.137922,-1.309836,0.471116,-2.780286,5.431107e-03,1.932493e-02
19815,ENSSSCG00000051773,2.408691,-4.433786,2.050997,-2.161771,3.063580e-02,NaN
19817,ENSSSCG00000051776,8.199226,-2.130959,1.019445,-2.090313,3.658969e-02,9.372539e-02
19829,ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07

In [20]:
df_down.set_index("id", inplace = True)
df_down

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
id,,,,,,
ENSSSCG00000000092,32.015411,-1.254268,0.442818,-2.832469,4.619007e-03,1.691791e-02
ENSSSCG00000000197,8.740224,-2.010402,0.936963,-2.145657,3.190034e-02,8.376230e-02
ENSSSCG00000000232,3.315000,-3.851302,1.664316,-2.314045,2.066525e-02,5.894852e-02
ENSSSCG00000000258,17.796641,-1.387154,0.607078,-2.284968,2.231473e-02,6.281356e-02
ENSSSCG00000000368,58.881808,-1.065940,0.352353,-3.025204,2.484653e-03,9.961614e-03
...,...,...,...,...,...,...
ENSSSCG00000051721,15.490371,-1.855634,0.691739,-2.682564,7.306008e-03,2.486690e-02
ENSSSCG00000051750,30.137922,-1.309836,0.471116,-2.780286,5.431107e-03,1.932493e-02
ENSSSCG00000051773,2.408691,-4.433786,2.050997,-2.161771,3.063580e-02,NaN
ENSSSCG00000051776,8.199226,-2.130959,1.019445,-2.090313,3.658969e-02,9.372539e-02
ENSSSCG00000051795,23.144970,-4.811001,0.854785,-5.628317,1.819763e-08,2.179243e-07

In [19]:
df_gene = pd.read_csv("gene.bed", sep="\t")
df_gene.set_index("gene_id", inplace = True)
df_gene

,GeneSymbol,Chromosome,Class,Strand
gene_id,,,,
ENSSSCG00000048769,gene_sourceensembl,chr1:1-3782,NaN,+
ENSSSCG00000037372,gene_sourceensembl,chr1:9815-22152,NaN,-
ENSSSCG00000027257,PSMB1,chr1:23782-40033,protein_coding,+
ENSSSCG00000029697,FAM120B,chr1:96128-186749,protein_coding,-
ENSSSCG00000049216,gene_sourceensembl,chr1:108537-114011,NaN,-
...,...,...,...,...
ENSSSCG00000018092,ND6,chrMT:14739-15266,protein_coding,-
ENSSSCG00000018093,gene_sourceRefSeq,chrMT:15267-15335,NaN,-
ENSSSCG00000018094,CYTB,chrMT:15342-16481,protein_coding,+
ENSSSCG00000018095,gene_sourceRefSeq,chrMT:16482-16549,NaN,+
ENSSSCG00000018096,gene_sourceRefSeq,chrMT:16550-16613,NaN,-

In [27]:
df_gene.loc[df_down.index]["GeneSymbol"].to_csv("down_gene.txt", sep="\t")

In [28]:
df_gene.loc[df_up.index]["GeneSymbol"].to_csv("up_gene.txt", sep="\t")