In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_table("total_enhancer_histonesignal.txt",header=None)
df.columns = ["chr", "start", "end", "wt-k27ac_1", "wt-k27ac_2", "wt-input_1", "wt-input_2", "pi-k27ac_1", "pi-k27ac_2","pi-input_1", "pi-input_2","DEGs"]
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,pi-input_2,DEGs
0,chr4,82280000,82290000,506.0,469.0,76.0,86.0,259.0,309.0,48.0,83.0,pi_specific
1,chr13,198190000,198200000,520.0,639.0,97.0,70.0,750.0,1245.0,54.0,98.0,pi_specific
2,chr6,97110000,97120000,359.0,437.0,68.0,66.0,361.0,499.0,64.0,72.0,pi_specific
3,chr8,37650000,37660000,1334.0,1179.0,99.0,92.0,1571.0,2190.0,56.0,61.0,pi_specific
4,chr7,1820000,1830000,174.0,266.0,42.0,42.0,276.0,525.0,36.0,18.0,pi_specific

In [3]:
#calibrate depth
df["wt-k27ac_1nor"] = df["wt-k27ac_1"]/47
df["wt-k27ac_2nor"] = df["wt-k27ac_2"]/53
df["wt-igg_1nor"] = df["wt-input_1"]/10
df["wt-igg_2nor"] = df["wt-input_2"]/10
df["pi-k27ac_1nor"] = df["pi-k27ac_1"]/38
df["pi-k27ac_2nor"] = df["pi-k27ac_2"]/59
df["pi-igg_1nor"] = df["pi-input_1"]/8
df["pi-igg_2nor"] = df["pi-input_2"]/9
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,pi-input_2,DEGs,wt-k27ac_1nor,wt-k27ac_2nor,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor
0,chr4,82280000,82290000,506.0,469.0,76.0,86.0,259.0,309.0,48.0,83.0,pi_specific,10.765957,8.849057,7.6,8.6,6.815789,5.237288,6.00,9.222222
1,chr13,198190000,198200000,520.0,639.0,97.0,70.0,750.0,1245.0,54.0,98.0,pi_specific,11.063830,12.056604,9.7,7.0,19.736842,21.101695,6.75,10.888889
2,chr6,97110000,97120000,359.0,437.0,68.0,66.0,361.0,499.0,64.0,72.0,pi_specific,7.638298,8.245283,6.8,6.6,9.500000,8.457627,8.00,8.000000
3,chr8,37650000,37660000,1334.0,1179.0,99.0,92.0,1571.0,2190.0,56.0,61.0,pi_specific,28.382979,22.245283,9.9,9.2,41.342105,37.118644,7.00,6.777778
4,chr7,1820000,1830000,174.0,266.0,42.0,42.0,276.0,525.0,36.0,18.0,pi_specific,3.702128,5.018868,4.2,4.2,7.263158,8.898305,4.50,2.000000

In [4]:
df['wt-k27ac_mean'] = df[['wt-k27ac_1nor', 'wt-k27ac_2nor']].mean(axis=1)
df['wt-igg_mean'] = df[['wt-igg_1nor', 'wt-igg_2nor']].mean(axis=1)

In [5]:
df['pi-k27ac_mean'] = df[['pi-k27ac_1nor', 'pi-k27ac_2nor']].mean(axis=1)
df['pi-igg_mean'] = df[['pi-igg_1nor', 'pi-igg_2nor']].mean(axis=1)

In [6]:
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,...,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-igg_mean,pi-k27ac_mean,pi-igg_mean
0,chr4,82280000,82290000,506.0,469.0,76.0,86.0,259.0,309.0,48.0,...,7.6,8.6,6.815789,5.237288,6.00,9.222222,9.807507,8.10,6.026539,7.611111
1,chr13,198190000,198200000,520.0,639.0,97.0,70.0,750.0,1245.0,54.0,...,9.7,7.0,19.736842,21.101695,6.75,10.888889,11.560217,8.35,20.419269,8.819444
2,chr6,97110000,97120000,359.0,437.0,68.0,66.0,361.0,499.0,64.0,...,6.8,6.6,9.500000,8.457627,8.00,8.000000,7.941790,6.70,8.978814,8.000000
3,chr8,37650000,37660000,1334.0,1179.0,99.0,92.0,1571.0,2190.0,56.0,...,9.9,9.2,41.342105,37.118644,7.00,6.777778,25.314131,9.55,39.230375,6.888889
4,chr7,1820000,1830000,174.0,266.0,42.0,42.0,276.0,525.0,36.0,...,4.2,4.2,7.263158,8.898305,4.50,2.000000,4.360498,4.20,8.080731,3.250000

In [7]:
df["wt-k27ac_change"] = np.log2((df["wt-k27ac_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["pi-k27ac_change"] = np.log2((df["pi-k27ac_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,...,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-igg_mean,pi-k27ac_mean,pi-igg_mean,wt-k27ac_change,pi-k27ac_change
0,chr4,82280000,82290000,506.0,469.0,76.0,86.0,259.0,309.0,48.0,...,6.815789,5.237288,6.00,9.222222,9.807507,8.10,6.026539,7.611111,0.275934,-0.336728
1,chr13,198190000,198200000,520.0,639.0,97.0,70.0,750.0,1245.0,54.0,...,19.736842,21.101695,6.75,10.888889,11.560217,8.35,20.419269,8.819444,0.469272,1.211079
2,chr6,97110000,97120000,359.0,437.0,68.0,66.0,361.0,499.0,64.0,...,9.500000,8.457627,8.00,8.000000,7.941790,6.70,8.978814,8.000000,0.245270,0.166505
3,chr8,37650000,37660000,1334.0,1179.0,99.0,92.0,1571.0,2190.0,56.0,...,41.342105,37.118644,7.00,6.777778,25.314131,9.55,39.230375,6.888889,1.406276,2.509455
4,chr7,1820000,1830000,174.0,266.0,42.0,42.0,276.0,525.0,36.0,...,7.263158,8.898305,4.50,2.000000,4.360498,4.20,8.080731,3.250000,0.054091,1.313781

In [8]:
df.loc[df['wt-k27ac_change'] < 0, 'wt-k27ac_change'] = 0
df.loc[df['pi-k27ac_change'] < 0, 'pi-k27ac_change'] = 0
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,...,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-igg_mean,pi-k27ac_mean,pi-igg_mean,wt-k27ac_change,pi-k27ac_change
0,chr4,82280000,82290000,506.0,469.0,76.0,86.0,259.0,309.0,48.0,...,6.815789,5.237288,6.00,9.222222,9.807507,8.10,6.026539,7.611111,0.275934,0.000000
1,chr13,198190000,198200000,520.0,639.0,97.0,70.0,750.0,1245.0,54.0,...,19.736842,21.101695,6.75,10.888889,11.560217,8.35,20.419269,8.819444,0.469272,1.211079
2,chr6,97110000,97120000,359.0,437.0,68.0,66.0,361.0,499.0,64.0,...,9.500000,8.457627,8.00,8.000000,7.941790,6.70,8.978814,8.000000,0.245270,0.166505
3,chr8,37650000,37660000,1334.0,1179.0,99.0,92.0,1571.0,2190.0,56.0,...,41.342105,37.118644,7.00,6.777778,25.314131,9.55,39.230375,6.888889,1.406276,2.509455
4,chr7,1820000,1830000,174.0,266.0,42.0,42.0,276.0,525.0,36.0,...,7.263158,8.898305,4.50,2.000000,4.360498,4.20,8.080731,3.250000,0.054091,1.313781

In [9]:
h3k27ac = df[["chr","start","end","wt-k27ac_change","pi-k27ac_change","DEGs"]] 
h3k27ac.head()
h3k27ac.to_csv("enhancer_h3k27ac_change.txt", sep="\t", index=False)