In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("GSE179184_a549.condense.rnaseq.all.rpkm_genename.tsv", sep="\t")
df

,RefeSeq ID,gene,chr,start,end,strand,Mock rpt1 RPKM,6hpi rpt1 RPKM,24hpi rpt1 RPKM,Mock rpt2 RPKM,6hpi rpt2 RPKM,24hpi rpt2 RPKM,IFNbeta 6h RPKM,Mock rpt3 RPKM,24hpi rpt3 RPKM
0,NR_046630,NCBP2-AS1,chr3,196666748,196669405,+,0.000,0.000,0.192,0.131,0.038,0.000,0.152,0.224,0.235
1,NR_046598,FGF12-AS2,chr3,192232811,192234362,+,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,NR_046514,SOX21-AS1,chr13,95364970,95368199,+,0.000,0.000,0.000,0.000,0.036,0.000,0.057,0.052,0.000
3,NR_106918,MIR6859-1,chr15,102513727,102513794,-,1.635,0.000,0.000,1.363,1.601,0.000,1.267,0.466,0.000
4,NR_107062,MIR6859-2,chr15,102513727,102513794,-,1.090,0.000,0.000,1.363,1.601,0.000,1.267,0.466,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28111,NM_001355213,OR10D3,chr11,124055923,124056952,+,0.000,0.000,0.209,0.000,0.000,0.000,0.000,0.000,0.000
28112,NM_012240,SIRT4,chr12,120740124,120751045,+,0.758,0.403,0.534,0.394,0.446,1.455,0.493,0.104,0.164
28113,NM_030979,PABPC3,chr13,25670276,25672704,+,6.305,10.275,2.384,10.491,12.258,3.210,6.261,6.324,4.240
28114,NM_080671,KCNE4,chr2,223916648,223920357,+,1.933,1.437,1.350,1.542,1.745,3.130,6.642,1.388,0.860
28115,NM_033630,SCAND1,chr20,34541539,34542548,-,19.351,21.763,1.073,24.622,26.545,3.144,24.570,14.996,4.867

In [26]:
gene = pd.read_csv("commgene.txt", header = None)
gene.columns = ["gene"]
gene

       gene
0       A2M
1     ABHD6
2     ABTB2
3     ACADS
4     ACOX2
..      ...
271    ZFP1
272  ZNF292
273  ZNF335
274  ZNF576
275  ZNF623

[276 rows x 1 columns]

In [27]:
df_out = pd.merge(df, gene, on="gene")
df_out

,RefeSeq ID,gene,chr,start,end,strand,Mock rpt1 RPKM,6hpi rpt1 RPKM,24hpi rpt1 RPKM,Mock rpt2 RPKM,6hpi rpt2 RPKM,24hpi rpt2 RPKM,IFNbeta 6h RPKM,Mock rpt3 RPKM,24hpi rpt3 RPKM
0,NM_001136051,LRIG3,chr12,59265937,59313327,-,2.588,2.585,2.471,2.337,2.617,4.092,3.645,2.326,1.896
1,NM_052924,RHPN1,chr8,144451046,144466391,+,3.911,4.219,0.903,4.051,4.334,1.271,6.730,3.908,1.939
2,NM_012319,SLC39A6,chr18,33688494,33709303,-,18.202,12.840,1.446,13.917,13.366,1.698,17.184,15.016,5.520
3,NM_004426,PHC1,chr12,9067105,9094060,+,0.557,0.334,0.140,0.296,0.424,0.163,0.790,0.442,0.330
4,NR_037577,TMEM222,chr1,27648736,27662891,+,8.446,9.973,1.410,8.608,8.017,1.282,10.464,8.169,3.708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,NM_199262,SP6,chr17,45922274,45933063,-,0.938,0.509,0.355,0.742,0.866,0.242,0.555,0.345,0.400
269,NR_135637,ARHGDIB,chr12,15094965,15101830,-,1.145,0.944,0.000,0.474,0.325,0.000,0.275,0.676,0.178
270,NM_198793,CD47,chr3,107761941,107809935,-,11.034,9.034,0.507,8.390,8.140,0.867,11.348,8.100,3.481
271,NM_198524,TEX9,chr15,56657622,56738195,+,2.695,1.413,1.803,2.235,1.793,1.135,1.997,2.347,1.894
272,NM_012240,SIRT4,chr12,120740124,120751045,+,0.758,0.403,0.534,0.394,0.446,1.455,0.493,0.104,0.164

In [28]:
df_out[df_out["Mock rpt1 RPKM"] > 1]

,RefeSeq ID,gene,chr,start,end,strand,Mock rpt1 RPKM,6hpi rpt1 RPKM,24hpi rpt1 RPKM,Mock rpt2 RPKM,6hpi rpt2 RPKM,24hpi rpt2 RPKM,IFNbeta 6h RPKM,Mock rpt3 RPKM,24hpi rpt3 RPKM
0,NM_001136051,LRIG3,chr12,59265937,59313327,-,2.588,2.585,2.471,2.337,2.617,4.092,3.645,2.326,1.896
1,NM_052924,RHPN1,chr8,144451046,144466391,+,3.911,4.219,0.903,4.051,4.334,1.271,6.730,3.908,1.939
2,NM_012319,SLC39A6,chr18,33688494,33709303,-,18.202,12.840,1.446,13.917,13.366,1.698,17.184,15.016,5.520
4,NR_037577,TMEM222,chr1,27648736,27662891,+,8.446,9.973,1.410,8.608,8.017,1.282,10.464,8.169,3.708
5,NM_017785,SPDL1,chr5,169010777,169031781,+,25.165,25.000,3.578,33.960,33.301,7.513,20.220,26.249,13.829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NM_198202,POP5,chr12,121016848,121019201,-,16.527,16.466,1.162,20.240,19.560,0.906,18.200,16.422,6.266
267,NM_198488,FAM83H,chr8,144806103,144815949,-,16.783,18.200,2.970,11.319,11.946,2.354,14.257,8.343,4.031
269,NR_135637,ARHGDIB,chr12,15094965,15101830,-,1.145,0.944,0.000,0.474,0.325,0.000,0.275,0.676,0.178
270,NM_198793,CD47,chr3,107761941,107809935,-,11.034,9.034,0.507,8.390,8.140,0.867,11.348,8.100,3.481
271,NM_198524,TEX9,chr15,56657622,56738195,+,2.695,1.413,1.803,2.235,1.793,1.135,1.997,2.347,1.894